# https://taskfile.dev
version: '3'

silent: true

tasks:
  init:
    desc: Initialize environment
    deps:
      - task: docker:init

  build:
    desc: Build app
    cmds:
      - docker compose build

  run:
    desc: Run app
    cmds:
      - docker compose run --rm php bash

  default:
    desc: default
    cmds:
      - task --list-all
