# https://taskfile.dev
version: '3'

silent: true

tasks:
  init:
    desc: Initialize environment
    deps:
      - task: docker:init

  up:
    desc: Initialize environment
    cmds:
      - docker compose up

  default:
    desc: default
    cmds:
      - task --list-all
